"""esquema inicial

Revision ID: 2b503b310587
Revises: 
Create Date: 2026-08-28 20:12:11.517898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b503b310587'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('sede', sa.String(), nullable=False),
    sa.Column('numero_cajas_totales', sa.Integer(), nullable=False),
    sa.Column('capacidad_max_clientes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_almacenes_id'), 'almacenes', ['id'], unique=False)
    op.create_table('cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('cajero_asignado', sa.String(), nullable=True),
    sa.Column('tasa_servicio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cajas_id'), 'cajas', ['id'], unique=False)
    op.create_table('resultados_simulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('parametros_entrada', sa.JSON(), nullable=False),
    sa.Column('resultados', sa.JSON(), nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_simulacion_id'), 'resultados_simulacion', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_llegada', sa.DateTime(), nullable=False),
    sa.Column('hora_inicio_atencion', sa.DateTime(), nullable=True),
    sa.Column('hora_salida', sa.DateTime(), nullable=True),
    sa.Column('tiempo_espera', sa.Float(), nullable=True),
    sa.Column('tiempo_servicio', sa.Float(), nullable=True),
    sa.Column('caja_asignada_id', sa.Integer(), nullable=True),
    sa.Column('abandono', sa.Boolean(), nullable=True),
    sa.Column('simulacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caja_asignada_id'], ['cajas.id'], ),
    sa.ForeignKeyConstraint(['simulacion_id'], ['resultados_simulacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('simulacion_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['simulacion_id'], ['resultados_simulacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulacion_eventos_id'), 'simulacion_eventos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulacion_eventos_id'), table_name='simulacion_eventos')
    op.drop_table('simulacion_eventos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_resultados_simulacion_id'), table_name='resultados_simulacion')
    op.drop_table('resultados_simulacion')
    op.drop_index(op.f('ix_cajas_id'), table_name='cajas')
    op.drop_table('cajas')
    op.drop_index(op.f('ix_almacenes_id'), table_name='almacenes')
    op.drop_table('almacenes')
    # ### end Alembic commands ###
